version: '2'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=dev
    ports:
      - "3000:3000"
    volumes:
      - ".:/src"
    depends_on:
      - mongo
    command:
      node .
    tty: true

  mongo:
    image: mongo:3.0
    ports:
      - "27017:27027"
    command: "mongod"

